<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_promo</name>
   <tag></tag>
   <elementGuidId>94061493-3e48-43cd-9e3f-da2f340d238b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/p[@id='hyperlink_promo']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
